### ISSUE TITLE
[MINOR BUGFIX] Member cards responsivness

### ISSUE THREAD

**Issue by RealRedStar** [DavidHadek/ZSWI#105]
Member cards are too small and when the student pill is checked, it is on the other side.
![cards_too_small](https://github.com/DavidHadek/ZSWI/assets/78258260/b7b33c9e-c8ba-4ca0-9e3b-ff38c5cb2eb3)
![pills](https://github.com/DavidHadek/ZSWI/assets/78258260/55701548-4bc0-46d1-b91a-3eea483a2b75)

**Comment by DavidHadek** [comment]
The responsiveness of the site is addressed in the branch feature/viewResponsivness
